baseURL = 'https://l4l.org/'
languageCode = 'zh-cn'
title = '求学之路|Left4Learning'
theme = "DoIt"

[author]
  name = "Yansong Chen"  # 必填：你的花名或真名（如 "李雷" 或 "Li Lei"）
  link = "https://github.com/你的GitHubID"  # 选填：点击你的名字时跳转的链接
  email = "你的邮箱@example.com"  # 选填：你的联系邮箱
  avatar = "/images/avatar.png"  # 选填：你的头像路径（图片需放在 static/images/ 目录下）

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

